### ISSUE TITLE
COPY failed: stat /var/lib/docker/tmp/docker-builder172684371/proxysql.cnf.template: no such file or directory

### ISSUE THREAD

**Issue by liangruibupt** [aws-samples/serverless-refarch-for-proxysql#11]
Removing intermediate container f555f3fe9209
 ---> 17467866dc8e
Step 4/7 : COPY proxysql.cnf.template /root/proxysql.cnf.template
COPY failed: stat /var/lib/docker/tmp/docker-builder172684371/proxysql.cnf.template: no such file or directory
[100%] fail: docker build --tag cdkasset-7962514ca2f72e2683218adac1b3957df74e95acf24ba1770295ec42285ed01d . exited with error code 1

 ❌  ProxysqlFargateStack failed: Error: Failed to publish one or more assets. See the error messages above for more information.
Failed to publish one or more assets. See the error messages above for more information.

**Comment by pahud** [comment]
fixed https://github.com/aws-samples/serverless-refarch-for-proxysql/commit/b2fbc1ced5d325c7898c7d71eaa2ab319f7c7499

please try again
