### ISSUE TITLE
[feature request]Support specify the subnet id list not vpc

### ISSUE THREAD

**Issue by liangruibupt** [aws-samples/serverless-refarch-for-proxysql#12]
Right now, if I use the existed VPC, I need make sure all private subnets in this VPC must in different AZs. If I my private subnet more than AZ number: e.g 6 subnets cross 3 AZs, it will cause deployment failure.

Feature request:
Support use specify the subnet id list which cross different AZs or set VPC attributes to avoid above issue.

**Comment by pahud** [comment]
@liangruibupt  Thanks for the feedback.

Will put this in the roadmap and implement soon.

**Comment by pahud** [comment]
Please check this new feature in the latet [v2.2.1](https://github.com/aws-samples/serverless-refarch-for-proxysql/releases/tag/v2.2.1).

Have fun and any feedbacks are highly appreciated.
