### ISSUE TITLE
fix the document typo

### ISSUE THREAD

**Issue by liangruibupt** [aws-samples/serverless-refarch-for-proxysql#13]
Go to AWS Secrets Manager again, find the secret DBClusterDatabaseSecret* and copy its value. Replace the *** below.

It should be `ProxysqlFargateStack-auroraMasterSecret` not `DBClusterDatabaseSecret*`

Now get back to the NLB> terminal
```
WRITER> SELECT * FROM demo.tasks;
```
The content should be all in sync.

It should be
```
NLB> SELECT * FROM demo.tasks;
```

**Comment by pahud** [comment]
Thanks @liangruibupt
