### ISSUE TITLE
[feature request]support custom master secret for custom backend

### ISSUE THREAD

**Issue by liangruibupt** [aws-samples/serverless-refarch-for-proxysql#14]
Right now for customer existed mysql, we till need use the ProxysqlFargateStack-auroraMasterSecret to login. 
Customer want to support use the existed mysql credential for proxySQL cluster to connect existed mysql

**Comment by pahud** [comment]
Thanks for the feedback.

I think we can provide a `masterSecret: Secret` property in `CustomBackend` interface to allow user pass in their master password from their existing Secret from secret manager.

https://github.com/aws-samples/serverless-refarch-for-proxysql/blob/0e7cf50a524df192818307d4d38e1246d3e3838b/lib/index.ts#L53-L80

What do you think?

**Comment by pahud** [comment]
Please check this new feature in the latet [v2.2.1](https://github.com/aws-samples/serverless-refarch-for-proxysql/releases/tag/v2.2.1).

Have fun and any feedbacks are highly appreciated.
