### ISSUE TITLE
Code not supported in new version CDK after 1.65

### ISSUE THREAD

**Issue by 0dd** [aws-samples/serverless-refarch-for-proxysql#17]
When commanding cdk for compiling

`SError: ⨯ Unable to compile TypeScript:
lib/index.ts:113:7 - error TS2345: Argument of type '{ engine: IClusterEngine; masterUser: { username: string; }; instanceProps: { instanceType: ec2.InstanceType; vpc: ec2.IVpc; }; removalPolicy: cdk.RemovalPolicy.DESTROY; }' is not assignable to parameter of type 'DatabaseClusterProps'.
  Object literal may only specify known properties, and 'masterUser' does not exist in type 'DatabaseClusterProps'.

113       masterUser: {
          ~~~~~~~~~~~~~
114         username: DB_MASTER_USERNAME ?? 'admin',
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
115       },`

It may rasied for `rds: DatabaseInstanceProps and DatabaseInstanceFromSnapshotProps -
masterUsername, masterUserPassword and masterUserPasswordEncryptionKey moved
to credentials as a new Credentials class.`

in https://github.com/aws/aws-cdk/releases/tag/v1.65.0

**Comment by DanyC97** [comment]
you are right @0dd  the code doesn't work.
i have a local fork which works with 

```
➜ cdk --version                             
1.77.0 (build a941c53)
```

not sure if @pahud will accept a PR but will send one in case will help others

**Comment by pahud** [comment]
Hi I just refreshed this project with #19 #20 and it should work with latest CDK now. Please let me know if it works in your environment.
